sudo: false
os:
  - linux
addons:
  apt:
    sources:
    - boost-latest
    - ubuntu-sdk-team
    packages:
    - qt5-qmake
    - qtbase5-dev
    - qtdeclarative5-dev
    - qttools5-dev
    - qttools5-dev-tools
    - qt5-default
    - build-essential
    - libdb++-dev
    - libboost1.55-all-dev
    - autoconf
    - libssl-dev
    - libprotobuf-dev
    - protobuf-compiler
    - libqrencode-dev
    - libtool
    - libminiupnpc-dev
before_install:
  - chmod 755 src/leveldb/build_detect_platform
  - cd src/secp256k1
  - chmod 755 *
  - mkdir build-aux
  - mkdir build-aux/m4
  - ./autogen.sh
  - ./configure
  - make
  - export PATH=$PATH:$PWD/Transfercoin/src/secp256k1
  - export PATH=$PATH:$PWD/Transfercoin/src/secp256k1/include
  - export PATH=$PATH:$PWD/Transfercoin/src/secp256k1/src
  - cd ../..
script: 
  - cd src
  - make -f makefile.unix
