sudo: false
os:
  - linux
cache: 
  apt: true
  directories:
  - $HOME/transferdev/Transfercoin/src/leveldb
  - $HOME/transferdev/Transfercoin/src/secp256k1
  - $HOME/infernoman/Transfercoin/src/leveldb
  - $HOME/infernoman/Transfercoin/src/secp256k1
addons:
  apt:
    sources:
    - boost-latest
    - ubuntu-sdk-team
    packages:
    - build-essential
    - libdb++-dev
    - libboost1.55-all-dev
    - autoconf
    - libssl-dev
    - libprotobuf-dev
    - protobuf-compiler
    - libqrencode-dev
    - libgmp-dev
    - libtool
    - libminiupnpc-dev
before_install:
  - chmod 755 src/leveldb/build_detect_platform
script: 
  - cd src
  - make -f makefile.unix
