sudo: required
dist: trusty
os:
  - linux
addons:
  apt:
    sources:
    - boost-latest
    - ubuntu-sdk-team
    packages:
    - build-essential
    - libdb++-dev
    - libboost1.55-all-dev
    - autoconf
    - protobuf-compiler
    - libtool
    - libminiupnpc-dev
    - libqrencode-dev
    - libprotobuf-dev
    - libssl-dev
    - libgmp3-dev
    - libqt5gui5
    - qtbase5-dev
    - libqt5dbus5
    - qttools5-dev
    - qttools5-dev-tools
before_install:
  - chmod 755 src/leveldb/build_detect_platform
  - sudo sed -i 's/us-central1.gce/us-central1.gce.clouds/' /etc/apt/sources.list && sudo apt-get update
script:
  - qmake -qt=qt5 USE_UPNP=-
  - make
  - cd src
  - make -f makefile.unix
